<?php

use Illuminate\Database\Seeder;

use Carbon\Carbon;

class ServiceTypesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('service_types')->truncate();
    	DB::table('service_peak_hours')->truncate();
        DB::table('service_types')->insert([
        [
            'name' => 'Electrician',
            'provider_name' => 'Electrician',
            'parent_id' => 0,
            'fixed' => 20,
            'price' => 10,
            'status' => 1,
            'calculator' => 'FIXED',
            'marker' => asset('img/cars/sedan_marker.png'),
            'image' => url('img/services/electrician.jpg'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'name' => 'Plumbing',
            'provider_name' => 'Plumber',
            'parent_id' => 0,
            'fixed' => 20,
            'price' => 10,
            'status' => 1,
            'calculator' => 'FIXED',
            'marker' => asset('img/cars/sedan_marker.png'),
            'image' => url('img/services/plumbing.jpg'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'name' => 'Carpenter',
            'provider_name' => 'Carpenter',
            'parent_id' => 0,
            'fixed' => 20,
            'price' => 10,
            'status' => 1,
            'calculator' => 'FIXED',
            'marker' => asset('img/cars/sedan_marker.png'),
            'image' => url('img/services/carpenter.jpg'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'name' => 'Mechanic',
            'provider_name' => 'Mechanic',
            'parent_id' => 0,
            'fixed' => 20,
            'price' => 10,
            'status' => 1,
            'calculator' => 'FIXED',
            'marker' => asset('img/cars/sedan_marker.png'),
            'image' => url('img/services/mechanic.jpg'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'name' => 'Electrician - 1 ',
            'provider_name' => 'Electrician',
            'parent_id' => 1,
            'fixed' => 20,
            'price' => 10,
            'status' => 1,
            'calculator' => 'FIXED',
            'marker' => asset('img/cars/sedan_marker.png'),
            'image' => url('img/services/electrician.jpg'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'name' => 'Electrician -2 ',
            'provider_name' => 'Plumber',
            'parent_id' => 1,
            'fixed' => 20,
            'price' => 10,
            'status' => 1,
            'calculator' => 'FIXED',
            'marker' => asset('img/cars/sedan_marker.png'),
            'image' => url('img/services/plumbing.jpg'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'name' => 'Plumber -1',
            'provider_name' => 'Carpenter',
            'parent_id' => 2,
            'fixed' => 20,
            'price' => 10,
            'status' => 1,
            'calculator' => 'FIXED',
            'marker' => asset('img/cars/sedan_marker.png'),
            'image' => url('img/services/carpenter.jpg'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'name' => 'Plumber -2 ',
            'provider_name' => 'Mechanic',
            'parent_id' => 2,
            'fixed' => 20,
            'price' => 10,
            'status' => 1,
            'calculator' => 'FIXED',
            'marker' => asset('img/cars/sedan_marker.png'),
            'image' => url('img/services/mechanic.jpg'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'name' => 'Carpenter - 1 ',
            'provider_name' => 'Electrician',
            'parent_id' => 3,
            'fixed' => 20,
            'price' => 10,
            'status' => 1,
            'calculator' => 'FIXED',
            'marker' => asset('img/cars/sedan_marker.png'),
            'image' => url('img/services/electrician.jpg'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'name' => 'Carpenter -2 ',
            'provider_name' => 'Plumber',
            'parent_id' => 3,
            'fixed' => 20,
            'price' => 10,
            'status' => 1,
            'calculator' => 'FIXED',
            'marker' => asset('img/cars/sedan_marker.png'),
            'image' => url('img/services/plumbing.jpg'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'name' => 'Mechanic -1',
            'provider_name' => 'Carpenter',
            'parent_id' => 4,
            'fixed' => 20,
            'price' => 10,
            'status' => 1,
            'calculator' => 'FIXED',
            'marker' => asset('img/cars/sedan_marker.png'),
            'image' => url('img/services/carpenter.jpg'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
        [
            'name' => 'Mechanic -2 ',
            'provider_name' => 'Mechanic',
            'parent_id' => 4,
            'fixed' => 20,
            'price' => 10,
            'status' => 1,
            'calculator' => 'FIXED',
            'marker' => asset('img/cars/sedan_marker.png'),
            'image' => url('img/services/mechanic.jpg'),
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ],
    ]);
}
}
